jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: ./build.sh --target=CI
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: ./build.sh --target=CI-pack
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: Artifacts/

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: .\build.ps1  --target=CI
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
