jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: ./build.sh -target=CI
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: ./build.sh -target=CI-pack
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: Artifacts/

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: .\build.ps1  -target=CI
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
