variables:
  - group: Secrets

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          ./build.sh --target=CI --github-user "$(GITHUB_USER)" --github-pat "$(GITHUB_PAT)"
        displayName: "Run Cake with GitHub Authentication"
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'

  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - script: echo "GITHUB_USER=$(GITHUB_USER)"
        displayName: "Check if GitHub User is Set"
      - script: |
          ./build.sh --target=CI --github-user "$(GITHUB_USER)" --github-pat "$(GITHUB_PAT)"
        displayName: "Run Cake with GitHub Authentication"
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: Artifacts/

  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - powershell: |
          .\build.ps1 --target=CI --github-user "$(GITHUB_USER)" --github-pat "$(GITHUB_PAT)"
        displayName: "Run Cake with GitHub Authentication"
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
